"""Trains a tiny LlamaForCausalLM (transformers) from scratch on CPU on
sequences generated by our own synthetic SCM (`seq2cause.scm.NonlinearSCM`),
then runs the "full" vs. "atomic" / "windowed" / "independent_mediator"
intervention strategies against the *trained* (imperfect, non-oracle) model
and reports per-lag recall.

This complements `scripts/snr_diagnostic.py`, which uses the SCM's own exact
conditional as an "oracle" model (epsilon = 0) to isolate the
`do_interventions` construction from model-approximation error. Running the
same comparison against a real, imperfectly-trained autoregressive model
checks whether Chadyuk et al.'s (2026) lag>=2 collapse -- and the relative
ranking of the alternative constructions -- still holds once genuine model
approximation error is layered on top.

Proper eval / stability check
------------------------------
A single evaluation run only tells you the recall/CMI *given one particular
draw* of do-intervention noise particles. Before trusting "strategy X beats
strategy Y" or "lag>=2 recall is Z", this script re-evaluates the SAME
trained model against the SAME held-out sequences (and the SAME exact
ground-truth adjacency) `--n-stability-repeats` times, each time with an
independently re-seeded particle draw, and reports mean +/- std for the
selected tau, per-lag recall, and the median-CMI true/false-edge separation
across repeats. Large spread relative to the mean is the concrete, testable
signature of "the intervention probabilities are not stable" (either too few
particles, or the underlying signal is not much above the noise floor) as
opposed to "the intervention is not working at all" (median-CMI true/false
separation itself is small or inconsistent in sign across repeats).

Runs in a couple of minutes on a laptop CPU with the defaults below. Increase
`--steps`/`--vocab-size` for a better-converged model on a harder task (see
the printed train loss vs. H_max), or `--n-eval-sequences`/`--n-particles`/
`--n-stability-repeats` for a statistically more robust reading.

Usage:
    python scripts/train_and_test_lagged_effects.py
"""

from __future__ import annotations

import argparse
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import torch  # noqa: E402
import torch.nn.functional as F  # noqa: E402, N812 (standard PyTorch convention)

from seq2cause.adapters import HFModelAdapter  # noqa: E402
from seq2cause.diagnostics import (  # noqa: E402
    compare_intervention_strategies,
    estimate_oracle_score,
    ground_truth_adjacency,
    recall_by_lag_with_tau_by_lag,
)
from seq2cause.scm import NonlinearSCM  # noqa: E402
from seq2cause.threshold import (  # noqa: E402
    fit_exponential_lag_threshold,
    fit_power_law_lag_threshold,
    gmm_threshold,
    mad_threshold,
    otsu_threshold,
    percentile_threshold,
    pooled_f1_for_tau_by_lag,
    select_threshold_by_validation,
    select_thresholds_by_group,
)

STRATEGY_ORDER = ("full", "atomic", "windowed", "independent_mediator", "in_distribution_noise")

# Every per-lag thresholding scheme compared in this script. "shared" and
# "tailored"/"exponential" are supervised (need edge/non-edge labels to
# select tau); "mad"/"percentile"/"otsu"/"gmm" are unsupervised
# anomaly-detection-style cutoffs computed from the score distribution alone
# (labels are only used afterwards, to *evaluate* how good the unsupervised
# cutoff turned out to be) -- see threshold.py module docstring on each.
SCHEME_ORDER = (
    "shared", "tailored", "exponential", "power_law", "mad", "percentile", "otsu", "gmm",
)
UNSUPERVISED_SCHEMES = {
    "mad": mad_threshold,
    "percentile": percentile_threshold,
    "otsu": otsu_threshold,
    "gmm": lambda scores: gmm_threshold(scores).tau,
}


def _unsupervised_tau_by_lag(
    fn, lag_scores_t: torch.Tensor, lag_groups_t: torch.Tensor, max_lag: int, min_group_size: int = 8
) -> dict[int, float]:
    """Applies an unsupervised, label-free threshold function `fn` (e.g.
    `mad_threshold`) separately to each lag's own pooled score population,
    falling back to the whole population's threshold when a lag has too few
    samples to fit reliably -- mirroring `select_thresholds_by_group`'s
    fallback semantics, but without ever touching labels."""
    global_tau = fn(lag_scores_t)
    tau_by_lag = {}
    for lag in range(1, max_lag + 1):
        group_scores = lag_scores_t[lag_groups_t == lag]
        if group_scores.numel() >= min_group_size:
            try:
                tau_by_lag[lag] = fn(group_scores)
                continue
            except ValueError:
                pass
        tau_by_lag[lag] = global_tau
    return tau_by_lag



# Backward-compatible alias -- the adapter now lives in `seq2cause.adapters`
# as a public, reusable piece of the package (see README Quick Start), but
# keeps this name here since other scripts (e.g. simulate_threshold_law.py)
# import it from this module.
TrainedModelAdapter = HFModelAdapter


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--vocab-size", type=int, default=60)
    p.add_argument("--memory", type=int, default=3)
    p.add_argument("--seq-len", type=int, default=20)
    p.add_argument("--context", type=int, default=3)
    p.add_argument("--sparsity", type=float, default=0.9)
    p.add_argument(
        "--decay-rate",
        type=float,
        default=1.0,
        help="Exponential lag-decay rate for the SCM's linear term (paper default=1.0, "
        "which concentrates almost all true-edge signal at lag=1; pass a smaller value "
        "e.g. 0.3 to get comparable signal strength -- and true edges -- across deeper lags.",
    )
    p.add_argument("--hidden-size", type=int, default=32)
    p.add_argument("--num-layers", type=int, default=2)
    p.add_argument("--num-heads", type=int, default=2)
    p.add_argument("--steps", type=int, default=300)
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--lr", type=float, default=3e-3)
    p.add_argument("--n-eval-sequences", type=int, default=5)
    p.add_argument("--n-particles", type=int, default=24)
    p.add_argument("--n-counterfactuals", type=int, default=6)
    p.add_argument("--window-k", type=int, default=2)
    p.add_argument("--delta", type=float, default=0.05)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument(
        "--n-stability-repeats",
        type=int,
        default=1,
        help="Re-run the evaluation this many times with independently re-seeded "
        "do-intervention particle draws (same trained model, same held-out sequences, "
        "same ground truth) to check whether recall/CMI are stable or noise-dominated.",
    )
    p.add_argument(
        "--n-oracle-score-sequences",
        type=int,
        default=200,
        help="Number of fresh (held-out) sequences used to estimate the trained model's "
        "oracle score epsilon_hat = (loss - H(P)) / (H_max - H(P)) -- see Assumption 3.6 / "
        "Eq. 22. H(P) is computed exactly (Monte Carlo over the SCM's own exact "
        "conditional, not approximated by a validation-loss floor).",
    )
    p.add_argument(
        "--results-json",
        type=str,
        default=None,
        help="If set, dumps all results (oracle score, tau selections, per-lag recall for the "
        "shared/tailored/exponential-decay-fit thresholding schemes) to this JSON path.",
    )
    p.add_argument(
        "--save-model",
        type=str,
        default=None,
        help="If set, saves the trained model (HF `save_pretrained`) to this directory after "
        "training, so a later run can reuse the exact same trained model via --load-model "
        "instead of retraining -- useful when only sweeping evaluation-time parameters "
        "(e.g. --n-particles) and wanting to hold the trained model fixed.",
    )
    p.add_argument(
        "--load-model",
        type=str,
        default=None,
        help="If set, loads a previously --save-model'd model from this directory instead of "
        "training a new one (skips train_tiny_llama entirely).",
    )
    return p.parse_args(argv)


def load_tiny_llama(path: str):
    from transformers import LlamaForCausalLM

    model = LlamaForCausalLM.from_pretrained(path)
    model.eval()
    return model


def train_tiny_llama(scm: NonlinearSCM, args: argparse.Namespace):
    from transformers import LlamaConfig, LlamaForCausalLM

    config = LlamaConfig(
        vocab_size=scm.vocab_size,
        hidden_size=args.hidden_size,
        intermediate_size=args.hidden_size * 2,
        num_hidden_layers=args.num_layers,
        num_attention_heads=args.num_heads,
        num_key_value_heads=args.num_heads,
        max_position_embeddings=args.seq_len + 8,
    )
    model = LlamaForCausalLM(config)
    model.train()
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)

    h_max = torch.log(torch.tensor(float(scm.vocab_size)))
    for step in range(args.steps):
        batch = scm.sample_sequence(length=args.seq_len, batch_size=args.batch_size)
        input_ids = batch[:, :-1]
        labels = batch[:, 1:]
        logits = model(input_ids=input_ids).logits
        loss = F.cross_entropy(logits.reshape(-1, scm.vocab_size), labels.reshape(-1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if step % max(1, args.steps // 6) == 0 or step == args.steps - 1:
            print(f"  step {step:4d}/{args.steps}  loss={loss.item():.3f}  (H_max={h_max.item():.3f} nats)")

    model.eval()
    return model


def evaluate_once(
    adapter: TrainedModelAdapter,
    eval_sequences: torch.Tensor,
    adjacencies: list[torch.Tensor],
    args: argparse.Namespace,
) -> dict:
    """Runs one independent do-intervention evaluation pass (fresh particle
    draws, via whatever the current global torch RNG state is) against the
    SAME trained model, held-out sequences, and exact ground-truth
    adjacencies. Returns per-strategy selected tau, per-lag recall, and
    median-CMI true/false-edge separation for this single pass.
    """
    per_sequence: list[tuple] = []  # (adjacency_suffix, {strategy: cmi_matrix})
    pooled_scores: dict[str, list[float]] = {name: [] for name in STRATEGY_ORDER}
    pooled_labels: dict[str, list[bool]] = {name: [] for name in STRATEGY_ORDER}
    pooled_lags: dict[str, list[int]] = {name: [] for name in STRATEGY_ORDER}
    snr_medians: dict[str, dict[str, list[float]]] = {
        name: {"true": [], "false": []} for name in STRATEGY_ORDER
    }

    for i in range(args.n_eval_sequences):
        seq = eval_sequences[i]
        adjacency = adjacencies[i]
        unigram_freqs = torch.bincount(seq, minlength=args.vocab_size).float() + 1.0

        results = compare_intervention_strategies(
            adapter,
            seq,
            context_len=args.context,
            adjacency=adjacency,
            n_particles=args.n_particles,
            window_k=args.window_k,
            tau=None,  # threshold selected per-strategy below, not hardcoded
            max_lag=args.memory,
            unigram_freqs=unigram_freqs,
        )
        adjacency_suffix = adjacency[args.context :, args.context :]
        per_sequence.append((adjacency_suffix, {name: res.cmi_matrix for name, res in results.items()}))
        lc = adjacency_suffix.shape[-1]
        lag_matrix = torch.tensor(
            [[q - j for q in range(lc)] for j in range(lc)]
        )  # lag_matrix[j, q] = q - j
        for name, res in results.items():
            pooled_scores[name].extend(res.cmi_matrix.flatten().tolist())
            pooled_labels[name].extend(adjacency_suffix.flatten().tolist())
            pooled_lags[name].extend(lag_matrix.flatten().tolist())
            for lag_stats in res.snr.values():
                if lag_stats["median_true"] == lag_stats["median_true"]:  # not NaN
                    snr_medians[name]["true"].append(lag_stats["median_true"])
                if lag_stats["median_false"] == lag_stats["median_false"]:
                    snr_medians[name]["false"].append(lag_stats["median_false"])

    # Select tau per strategy on this pass's own pooled scores/labels (see
    # Part 1: never compare strategies at one shared, arbitrary tau).
    selected_tau: dict[str, float] = {}
    tau_by_lag_schemes: dict[str, dict[str, dict[int, float]]] = {s: {} for s in SCHEME_ORDER}
    pooled_f1_schemes: dict[str, dict[str, float]] = {s: {} for s in SCHEME_ORDER}
    exponential_fit: dict[str, object] = {}
    power_law_fit: dict[str, object] = {}
    gmm_fit: dict[str, object] = {}

    for name in STRATEGY_ORDER:
        if not pooled_scores[name]:
            continue
        result = select_threshold_by_validation(
            torch.tensor(pooled_scores[name]), torch.tensor(pooled_labels[name]), delta=args.delta,
            emit_warnings=False,
        )
        selected_tau[name] = result.tau

        valid_mask = [lag > 0 for lag in pooled_lags[name]]  # exclude q<=j (not a real pair)
        lag_scores_t = torch.tensor([s for s, keep in zip(pooled_scores[name], valid_mask) if keep])
        lag_labels_t = torch.tensor([lb for lb, keep in zip(pooled_labels[name], valid_mask) if keep])
        lag_groups_t = torch.tensor([lag for lag, keep in zip(pooled_lags[name], valid_mask) if keep])

        # Supervised schemes: select/fit tau using the edge/non-edge labels.
        tau_by_lag_schemes["shared"][name] = {
            lag: selected_tau[name] for lag in range(1, args.memory + 1)
        }
        by_group = select_thresholds_by_group(
            lag_scores_t, lag_labels_t, lag_groups_t,
            delta=args.delta, min_group_size=4, fallback="global", emit_warnings=False,
        )
        tau_by_lag_schemes["tailored"][name] = {lag: res.tau for lag, res in by_group.items()}
        exponential_fit[name] = fit_exponential_lag_threshold(
            lag_scores_t, lag_labels_t, lag_groups_t, max_lag=args.memory,
        )
        tau_by_lag_schemes["exponential"][name] = exponential_fit[name].tau_by_lag
        power_law_fit[name] = fit_power_law_lag_threshold(
            lag_scores_t, lag_labels_t, lag_groups_t, max_lag=args.memory,
        )
        tau_by_lag_schemes["power_law"][name] = power_law_fit[name].tau_by_lag

        # Unsupervised, anomaly-detection-style schemes: select tau from the
        # score distribution alone (labels only used below, to evaluate it).
        for scheme_name, fn in UNSUPERVISED_SCHEMES.items():
            tau_by_lag_schemes[scheme_name][name] = _unsupervised_tau_by_lag(
                fn, lag_scores_t, lag_groups_t, max_lag=args.memory,
            )
        gmm_fit[name] = gmm_threshold(lag_scores_t)

        # Put every scheme's thresholds on the exact same footing: pooled F1
        # across ALL lags (lag>0 only), same population for every scheme.
        for scheme_name in SCHEME_ORDER:
            pooled_f1_schemes[scheme_name][name] = pooled_f1_for_tau_by_lag(
                lag_scores_t, lag_labels_t, lag_groups_t, tau_by_lag_schemes[scheme_name][name]
            )[0]

    recall_by_strategy_lag_schemes: dict[str, dict[str, dict[int, list[float]]]] = {
        scheme_name: {
            name: {lag: [] for lag in range(1, args.memory + 1)} for name in selected_tau
        }
        for scheme_name in SCHEME_ORDER
    }
    for adjacency_suffix, cmi_by_strategy in per_sequence:
        for name, cmi_matrix in cmi_by_strategy.items():
            for scheme_name in SCHEME_ORDER:
                r = recall_by_lag_with_tau_by_lag(
                    cmi_matrix, adjacency_suffix,
                    tau_by_lag=tau_by_lag_schemes[scheme_name][name], max_lag=args.memory,
                )
                for lag, value in r.items():
                    if value == value:  # not NaN
                        recall_by_strategy_lag_schemes[scheme_name][name][lag].append(value)

    return {
        "selected_tau": selected_tau,
        "tau_by_lag_schemes": tau_by_lag_schemes,
        "pooled_f1_schemes": pooled_f1_schemes,
        "recall_by_strategy_lag_schemes": recall_by_strategy_lag_schemes,
        "exponential_fit": exponential_fit,
        "power_law_fit": power_law_fit,
        "gmm_fit": gmm_fit,
        "snr_medians": snr_medians,
    }


def main(argv=None) -> None:
    args = parse_args(argv)
    torch.manual_seed(args.seed)

    print(f"=== Training a tiny LlamaForCausalLM on a NonlinearSCM (vocab={args.vocab_size}, "
          f"memory={args.memory}, hidden_size={args.hidden_size}, layers={args.num_layers}) ===")
    scm = NonlinearSCM(
        vocab_size=args.vocab_size,
        memory=args.memory,
        sparsity=args.sparsity,
        decay_rate=args.decay_rate,
        seed=args.seed,
    )
    if args.load_model:
        print(f"=== Loading previously-trained model from {args.load_model} (skipping training) ===")
        model = load_tiny_llama(args.load_model)
    else:
        model = train_tiny_llama(scm, args)
        if args.save_model:
            Path(args.save_model).mkdir(parents=True, exist_ok=True)
            model.save_pretrained(args.save_model)
            print(f"Saved trained model to {args.save_model}")
    adapter = TrainedModelAdapter(model, vocab_size=args.vocab_size)
    n_params = sum(p.numel() for p in model.parameters())

    oracle_gen = torch.Generator(device="cpu").manual_seed(args.seed + 2)
    oracle = estimate_oracle_score(
        adapter, scm, n_sequences=args.n_oracle_score_sequences, length=args.seq_len,
        generator=oracle_gen,
    )
    print(f"\nOracle score (on {args.n_oracle_score_sequences} fresh held-out sequences, "
          f"H(P) estimated exactly from the SCM's own conditional, not approximated by a "
          f"validation-loss floor): loss={oracle['loss']:.3f} nats, H(P)={oracle['h_p']:.3f} nats, "
          f"H_max={oracle['h_max']:.3f} nats, epsilon_hat={oracle['epsilon_hat']:.3f}")
    if oracle["epsilon_hat"] > 0.1:
        print(f"  [!] epsilon_hat={oracle['epsilon_hat']:.3f} is well outside the paper's own "
              f"characterized epsilon in [0, 0.1] regime (Table 2 used ~0.04-0.05) -- the model "
              f"is comparatively undertrained; treat lag>=2 numbers below with extra caution, "
              f"since more model-approximation noise compounds with the construction/DGP effects "
              f"this script is trying to isolate. Increase --steps/--hidden-size/--num-layers.")

    print(f"\n=== Evaluating do_interventions strategies against the TRAINED model "
          f"({args.n_stability_repeats} independent particle-draw repeat(s)) ===")
    # Ground truth (and which sequences we evaluate on) is fixed ONCE, with
    # its own dedicated seed, and reused across every stability repeat --
    # only the do-intervention particle noise varies between repeats.
    gt_gen = torch.Generator(device="cpu").manual_seed(args.seed + 1)
    eval_sequences = scm.sample_sequence(
        length=args.seq_len, batch_size=args.n_eval_sequences, generator=gt_gen
    )
    adjacencies = [
        ground_truth_adjacency(
            scm, eval_sequences[i], threshold=args.delta, n_counterfactuals=args.n_counterfactuals,
            generator=gt_gen,
        )
        for i in range(args.n_eval_sequences)
    ]
    n_true_edges = sum(int(adj.sum()) for adj in adjacencies)
    print(f"Total ground-truth edges across {args.n_eval_sequences} held-out sequences: {n_true_edges}")

    repeats = []
    for r in range(args.n_stability_repeats):
        torch.manual_seed(args.seed + 10_000 + r)  # fresh particle draws only
        repeats.append(evaluate_once(adapter, eval_sequences, adjacencies, args))

    # --- Report: per-strategy tau stability across repeats ---
    print(f"\nPer-strategy validation-selected tau, mean +/- std over "
          f"{args.n_stability_repeats} repeat(s) (delta={args.delta}):")
    for name in STRATEGY_ORDER:
        taus = [rep["selected_tau"][name] for rep in repeats if name in rep["selected_tau"]]
        if not taus:
            continue
        mean_tau = statistics.mean(taus)
        std_tau = statistics.stdev(taus) if len(taus) > 1 else 0.0
        cv = std_tau / mean_tau if mean_tau else float("nan")
        flag = "  <-- UNSTABLE (CV>0.5)" if cv == cv and cv > 0.5 else ""
        print(f"  {name:<22} tau={mean_tau:.4g} +/- {std_tau:.4g}  (CV={cv:.2f}){flag}")

    # --- Report: median CMI true-edge vs. non-edge separation (is there a signal at all?) ---
    print("\nMedian CMI, true edges vs. non-edges, mean +/- std over repeats "
          "(separation ~ 0 or sign-inconsistent => the intervention is not detecting anything, "
          "regardless of threshold):")
    for name in STRATEGY_ORDER:
        true_vals = [v for rep in repeats for v in rep["snr_medians"][name]["true"]]
        false_vals = [v for rep in repeats for v in rep["snr_medians"][name]["false"]]
        if not true_vals or not false_vals:
            print(f"  {name:<22} insufficient true/false samples to report")
            continue
        print(f"  {name:<22} true={statistics.mean(true_vals):.4g} +/- "
              f"{statistics.pstdev(true_vals):.4g}   "
              f"false={statistics.mean(false_vals):.4g} +/- {statistics.pstdev(false_vals):.4g}")

    # --- Report: per-lag recall for every thresholding scheme ---
    scheme_descriptions = {
        "shared": "SINGLE shared tau per strategy (one validation-swept tau, same at every lag)",
        "tailored": "TAU TAILORED TO EACH LAG (independent per-lag validation sweep)",
        "exponential": "3-parameter EXPONENTIAL-DECAY-TO-A-FLOOR tau(lag) curve (joint fit)",
        "power_law": "3-parameter SUB-LINEAR POWER-LAW tau(lag) = floor + (tau1-floor)*lag^-b (joint fit)",
        "mad": "unsupervised MAD (median + k*MAD) cutoff, per lag, no labels used to select tau",
        "percentile": "unsupervised 95th-percentile cutoff, per lag, no labels used to select tau",
        "otsu": "unsupervised Otsu (between-class-variance) cutoff, per lag, no labels used",
        "gmm": "unsupervised 2-component Gaussian-mixture crossover, per lag, no labels used",
    }
    for scheme_name in SCHEME_ORDER:
        print(f"\n=== Per-lag recall: {scheme_descriptions[scheme_name]} ===")
        for name in STRATEGY_ORDER:
            if name not in repeats[0]["recall_by_strategy_lag_schemes"][scheme_name]:
                continue
            f1s = [
                rep["pooled_f1_schemes"][scheme_name][name] for rep in repeats
                if name in rep["pooled_f1_schemes"][scheme_name]
            ]
            f1_str = f"  (pooled F1={statistics.mean(f1s):.3f}, mean over repeats)" if f1s else ""
            curve_str = ""
            if scheme_name == "exponential":
                fits = [rep["exponential_fit"][name] for rep in repeats if name in rep["exponential_fit"]]
                if fits:
                    t1 = statistics.mean(f.tau_at_lag1 for f in fits)
                    rate = statistics.mean(f.decay_rate for f in fits)
                    floor = statistics.mean(f.noise_floor for f in fits)
                    curve_str = f"  tau(lag)={floor:.4g}+({t1:.4g}-{floor:.4g})*exp(-{rate:.3g}*(lag-1))"
            elif scheme_name == "power_law":
                fits = [rep["power_law_fit"][name] for rep in repeats if name in rep["power_law_fit"]]
                if fits:
                    t1 = statistics.mean(f.tau_at_lag1 for f in fits)
                    exponent = statistics.mean(f.exponent for f in fits)
                    floor = statistics.mean(f.noise_floor for f in fits)
                    curve_str = f"  tau(lag)={floor:.4g}+({t1:.4g}-{floor:.4g})*lag^-{exponent:.3g}"
            elif scheme_name == "gmm":
                fits = [rep["gmm_fit"][name] for rep in repeats if name in rep["gmm_fit"]]
                if fits:
                    curve_str = f"  pooled-fit {fits[0].summary()}"
            print(f"  {name}:{f1_str}{curve_str}")
            for lag in range(1, args.memory + 1):
                taus_this_lag = [
                    rep["tau_by_lag_schemes"][scheme_name][name][lag]
                    for rep in repeats
                    if lag in rep["tau_by_lag_schemes"][scheme_name][name]
                ]
                tau_str = f"tau={statistics.mean(taus_this_lag):.4g}" if taus_this_lag else "tau=n/a"
                vals = [
                    statistics.mean(rep["recall_by_strategy_lag_schemes"][scheme_name][name][lag])
                    for rep in repeats
                    if rep["recall_by_strategy_lag_schemes"][scheme_name][name][lag]
                ]
                if not vals:
                    print(f"    lag={lag}: n/a (no true edges at this lag)  ({tau_str})")
                    continue
                mean_r = statistics.mean(vals)
                std_r = statistics.stdev(vals) if len(vals) > 1 else 0.0
                flag = "  <-- UNSTABLE (std>0.2)" if std_r > 0.2 else ""
                print(f"    lag={lag}: {mean_r:.3f} +/- {std_r:.3f}  ({tau_str}, "
                      f"n_repeats_with_data={len(vals)}){flag}")

    if args.results_json:
        _dump_results_json(args, oracle, n_true_edges, repeats, n_params)


def _dump_results_json(args, oracle, n_true_edges, repeats, n_params) -> None:
    import json

    def _mean_std(values: list[float]) -> list[float]:
        if not values:
            return [float("nan"), float("nan")]
        return [statistics.mean(values), statistics.stdev(values) if len(values) > 1 else 0.0]

    payload = {
        "settings": {
            "vocab_size": args.vocab_size, "memory": args.memory, "seq_len": args.seq_len,
            "context": args.context, "sparsity": args.sparsity, "decay_rate": args.decay_rate,
            "hidden_size": args.hidden_size, "num_layers": args.num_layers,
            "num_heads": args.num_heads, "steps": args.steps, "batch_size": args.batch_size,
            "lr": args.lr, "n_eval_sequences": args.n_eval_sequences,
            "n_particles": args.n_particles, "n_counterfactuals": args.n_counterfactuals,
            "window_k": args.window_k, "delta": args.delta, "seed": args.seed,
            "n_stability_repeats": args.n_stability_repeats, "model_params": n_params,
        },
        "oracle_score": oracle,
        "n_true_edges_total": n_true_edges,
        "strategies": {},
    }
    for name in STRATEGY_ORDER:
        if name not in repeats[0]["selected_tau"]:
            continue
        entry: dict = {
            "selected_tau": _mean_std([rep["selected_tau"][name] for rep in repeats]),
            "schemes": {},
        }
        for scheme_name in SCHEME_ORDER:
            scheme_entry: dict = {
                "pooled_f1": _mean_std(
                    [rep["pooled_f1_schemes"][scheme_name][name] for rep in repeats
                     if name in rep["pooled_f1_schemes"][scheme_name]]
                ),
                "recall_by_lag": {},
                "tau_by_lag": {},
            }
            for lag in range(1, args.memory + 1):
                scheme_entry["recall_by_lag"][str(lag)] = _mean_std(
                    [statistics.mean(rep["recall_by_strategy_lag_schemes"][scheme_name][name][lag])
                     for rep in repeats
                     if rep["recall_by_strategy_lag_schemes"][scheme_name][name][lag]]
                )
                taus = [
                    rep["tau_by_lag_schemes"][scheme_name][name].get(lag)
                    for rep in repeats if name in rep["tau_by_lag_schemes"][scheme_name]
                ]
                scheme_entry["tau_by_lag"][str(lag)] = _mean_std([t for t in taus if t is not None])
            entry["schemes"][scheme_name] = scheme_entry

        exp_fits = [rep["exponential_fit"][name] for rep in repeats if name in rep["exponential_fit"]]
        if exp_fits:
            entry["schemes"]["exponential"]["fit_params"] = {
                "tau_at_lag1": _mean_std([f.tau_at_lag1 for f in exp_fits]),
                "decay_rate": _mean_std([f.decay_rate for f in exp_fits]),
                "noise_floor": _mean_std([f.noise_floor for f in exp_fits]),
            }
        pow_fits = [rep["power_law_fit"][name] for rep in repeats if name in rep["power_law_fit"]]
        if pow_fits:
            entry["schemes"]["power_law"]["fit_params"] = {
                "tau_at_lag1": _mean_std([f.tau_at_lag1 for f in pow_fits]),
                "exponent": _mean_std([f.exponent for f in pow_fits]),
                "noise_floor": _mean_std([f.noise_floor for f in pow_fits]),
            }
        payload["strategies"][name] = entry

    out_path = Path(args.results_json)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2))
    print(f"\nResults written to {out_path}")


if __name__ == "__main__":
    main()
